layout_spectrum: 0.2455197
typography_spectrum: 0.8924731
color:
  saturation: 0.1935484
  lightness: 0.1505376
  brandStrength: 0.2043011
  rhythmicContrast: 0.1308244
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: fashiontechnology
